# Generated by Django 5.0.6 on 2024-06-24 11:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('oauth2_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offline', 'Disconnected'), ('online', 'Online'), ('ingame', 'In game')], default='offline', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=10)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to='transcendence.account')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to='transcendence.account')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.AddField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(related_name='friends+', through='transcendence.Friendship', to='transcendence.account'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player1_ready', models.BooleanField(default=False)),
                ('player2_ready', models.BooleanField(default=False)),
                ('created_for_queue', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('wait', 'Waiting for players'), ('starting', 'Starting'), ('started', 'Started'), ('finished', 'Finished')], default='wait', max_length=10)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='transcendence.account')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='transcendence.account')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='transcendence.account')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('islaunched', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('wait', 'Waiting for players'), ('launched', 'Tournament is full and has launched'), ('finished', 'Finished')], default='wait')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_tournament', to='transcendence.account')),
                ('stage1games', models.ManyToManyField(related_name='stage1games', to='transcendence.game')),
                ('stage2game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage2game', to='transcendence.game')),
                ('users', models.ManyToManyField(related_name='tournament_users', to='transcendence.account')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='linked_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_tournament', to='transcendence.tournament'),
        ),
    ]
