# Generated by Django 5.0.6 on 2024-07-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_account_tournament_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tournament_pseudo',
        ),
    ]
