import math


BALL_BASE_SPEED = 15
BALL_SPEED_INCREASE = 2
BALL_MAX_SPEED = 60
BALL_RADIUS = 0.5
MAX_BOUNCE_ANGLE = math.pi / 2
PADDLE_SPEED = 15
PADDLE_LENGTH = 4
PADDLE_WIDTH = 1
PADDLE_OFFSET = 2
FIELD_LENGTH = 30
FIELD_WIDTH = 20
CLIENT_FPS = 60
SERVER_FPS = 20
WIN_SCORE = 4
